#!/usr/bin/env ruby

require "puppet-unit"

#prepend current directory to LOAD_PATH
$:.unshift(".")

#load all tests
require "puppet-unit/helper.rb" if File.exist?("puppet-unit/helper.rb")

module_tests = []
module_test_dirs = ARGV[0] ? [ARGV[0]] : Dir[File.join("puppet-unit", "tests", "*")]

domain_names = PuppetUnit::Services::ConfigService.instance.get("libvirt")["domains"].keys

module_test_dirs.each do |module_test_dir|
  if File.directory?(module_test_dir)
    domain_names.each do |domain_name|
      PuppetUnit::Services::LogService.instance.debug("Loading test under #{module_test_dir} for domain #{domain_name}")
      module_tests << PuppetUnit::ModuleTest.new(module_test_dir, domain_name)
    end
  end
end

#run tests
test_runner = PuppetUnit::TestRunner.new(module_tests)
PuppetUnit::Services::LogService.instance.debug("Running tests")
test_runner.run

exit(1) unless module_tests.all?(&:passed?)