#!/usr/bin/env ruby

require "puppet-unit"

#prepend current directory to LOAD_PATH
$:.unshift(".")

#load all tests
require "puppet-unit/helper.rb" if File.exist?("puppet-unit/helper.rb")

module_tests = []
module_test_dirs = ARGV[0] ? [ARGV[0]] : Dir[File.join("puppet-unit", "tests", "*")]

module_test_dirs.each do |module_test_dir|
  if File.directory?(module_test_dir)
    PuppetUnit::Services::LogService.instance.debug("Loading test under #{module_test_dir}")
    module_tests << PuppetUnit::ModuleTest.new(module_test_dir)
  end
end

#run tests
test_runner = PuppetUnit::TestRunner.new(module_tests)
PuppetUnit::Services::LogService.instance.debug("Running tests")
test_runner.run

exit(1) unless module_tests.all?(&:passed?)