#!/usr/bin/env ruby

require "SUnit"

#prepend current direcotry to LOAD_PATH
$:.unshift(".")

#load all sunit tests
require "sunit/sunit_helper.rb" if File.exist?("sunit/sunit_helper.rb")
Dir[File.join("sunit", "**", "*.rb")].each { |file| require file }
test_klasses = ObjectSpace.each_object(::Class).select { |klass| klass < SUnit::Test }
tests = test_klasses.map(&:new)

#run tests
test_runner = SUnit::TestRunner.new(tests)
test_runner.run

exit(1) if tests.any?(&:failed?)